[build]
  command = "npm run build --prefix frontend"
  publish = "frontend/dist"

[build.environment]
  VITE_API_BASE_URL = "https://sf-wedding-api.rinzgroup.web.id/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
